Repository waset/yjzj-mini, pull requests merged in 2024-08, with the labels that each got.

#143 chore: 自动化设置 PR 标签
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/label-prs.yml
Labels: maintenance

#144 ci(github): 更新 release 模板
  .github/pr-labeler.yml
  .github/release-drafter.yml
Labels: configuration

#145 perf: 优化个人中心的展示和功能
  src/components/address/ItemCard.vue
  src/components/buys/AddressCard.vue
  src/components/buys/OrderinfoAddress.vue
  src/components/popularize/info.vue
  src/pages/me/me.vue
  src/utils/user/service.ts
Labels: maintenance, bugfix, enhancement

#147 fix: 优化遮罩层滚动
  src/components/common/Popup.vue
  src/components/product/custom/Optional.vue
  src/components/product/custom/Peripheral.vue
  src/components/product/custom/Relocation.vue
Labels: bugfix
